version: "3"
services:
    app:
        image: aloussase/datatable
        build:
            context: .
        restart: always
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
